name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env: 
# placeholders that will be managed by testcontainer
  NODE_ENV: "test"
  JWT_SECRET: "ci-test-valuet"
  DATABASE_URL: "ci-test-value"
  REDIS_URL: "ci-test-value"
  FRONTEND_URL: "ci-test-value"
  PINECONE_API_KEY: "ci-test-value"
  PINECONE_INDEX_NAME: "ci-test-value"
  OPENAI_API_KEY: "ci-test-value"
  ALTA_API_KEY: "ci-test-value"
  R2_ACCOUNT_ID: "ci-test-value"
  R2_API_TOKEN: "ci-test-value"
  R2_ACCESS_KEY: "ci-test-value"
  R2_SECRET_ACCESS_KEY: "ci-test-value"
  R2_BUCKET_NAME: "ci-test-value"
  R2_ENDPOINT: "ci-test-value"
  R2_PUBLIC_URL: "ci-test-value"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run prisma generate
        run: npx prisma generate

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build